run:
  timeout: 30m
  tests: false
  skip-files:
    - testinit.go
    - cmsys/fnv_hash.go
    - 00-config.go
    - ptttype/00-config-default.go
linters-settings:

  misspell:
    locale: US
    ignore-words:
      - visable
  gofmt:
  goimports:
  nolintlint:
    allow-unused: true
linters:
  enable:
    - gosec
    - misspell
    - gofmt
    - goimports
    - revive
    - nolintlint
issues:
  exclude:
    # we use underscores only for _postfix
    - don't use underscores
    # we use ALL_CAPS for constants
    - don't use ALL_CAPS
    # Simplify returning boolean expression (https://staticcheck.io/docs/checks#S1008)
    - S1008
    # A function argument is overwritten before its first use (https://staticcheck.io/docs/checks#SA4009)
    - SA4009
    # Skip weak rnd for now.
    - G404
    - comment on exported var.*should be of the form
    - func name will be used as .* by other packages, and that stutters; consider calling this'
    - type name will be used as .* by other packages, and that stutters; consider calling this'
    - 'indent-error-flow:'
    - 'exported:'
    - '`setBBottom` is unused'
    - '`pwcuSetByBit` is unused'
    - 'unused-parameter: parameter'
    - G115
  exclude-rules:
  exclude-use-default: true
