version: '2'
services:
  go-pttbbs:
    image: pttofficialapps/go-pttbbs:v0.14.2
    ports:
      - "127.0.0.1:3456:3456"
      - "127.0.0.1:8889:8888"
      - "127.0.0.1:48765:48763"
    restart: always
    volumes:
      - ${BBSHOME}:/home/bbs
