package api

func config() {
	JWT_SECRET = setBytesConfig("JWT_SECRET", JWT_SECRET)
	JWT_ISSUER = setStringConfig("JWT_ISSUER", JWT_ISSUER)
	GUEST = setStringConfig("GUEST", GUEST)

	EMAIL_JWT_SECRET = setBytesConfig("EMAIL_JWT_SECRET", EMAIL_JWT_SECRET)

	JWT_TOKEN_EXPIRE_TS = setIntConfig("JWT_TOKEN_EXPIRE_TS", JWT_TOKEN_EXPIRE_TS)

	EMAIL_JWT_TOKEN_EXPIRE_TS = setIntConfig("EMAIL_JWT_TOKEN_EXPIRE_TS", EMAIL_JWT_TOKEN_EXPIRE_TS)
}
